version: '3.8'

services:
  stable-diffusion-api:
    image: minha-api-cpu:latest
    build:
      context: https://github.com/fabricio1905harry/api-generator.git
      dockerfile: Dockerfile
    container_name: stable-diffusion-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - CUDA_VISIBLE_DEVICES=""
    volumes:
      - models_cache:/root/.cache/huggingface
    restart: unless-stopped
    networks:
      - api-network

volumes:
  models_cache:
    driver: local

networks:
  api-network:
    driver: bridge

