version: '3.8'

services:
  stable-diffusion-api:
    image: stable-diffusion-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - API_KEY=${API_KEY}
    volumes:
      - models_cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  models_cache:

